version: "3"

services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_USER: transacoes
      POSTGRES_PASSWORD: transacoes
      POSTGRES_DB: transacoes
  api1: &api
    build:
      context: .
    environment:
      DB_ENGINE: POSTGRES
      DB_DSN: host=postgres user=transacoes password=transacoes sslmode=disable
      GIN_MODE: release
    depends_on:
      - postgres
  api2:
    <<: *api
  nginx:
    image: nginx:1.25.3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 9999:9999
    depends_on:
      - api1
      - api2
