version: "3"

services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: transacoes
  api1: &api
    build:
      context: .
    environment:
      DB_ENGINE: POSTGRES
      DB_DSN: host=postgres user=$DB_USER password=$DB_PASSWORD sslmode=disable
      GIN_MODE: release
    depends_on:
      - postgres
  api2:
    <<: *api
  nginx:
    image: nginx:1.25.3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 9999:9999
    depends_on:
      - api1
      - api2
