// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cliente struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	Limite    pgtype.Int8
	Saldo     pgtype.Int8
}

type Transaco struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	Valor     pgtype.Int8
	Tipo      pgtype.Text
	Descricao pgtype.Text
	ClienteID pgtype.Int8
}
